Delete blob descendants from neo4j when deleting the blob
guardian/giant pull request #77
Opened 2022-10-10 18:04 UTC by joelochlann

Since [deletion was introduced](https://github.com/guardian/pfi/pull/441), we've never been cleaning up the neo4j structures underneath blobs. (This is relevant only for blobs with children, i.e. files containing other files such as zips, archives, mailboxes, etc.).

When we delete the ingestion at the end of the process, we delete all resources whose URI starts with the ingestion name:

https://github.com/guardian/giant/blob/512006051e4fc1e0fca4c545bf61713fd59fa3df/backend/app/services/manifest/Neo4jManifest.scala#L1017-L1036

However, URIs start again when there is an intervening blob, e.g.

1. collection
2. collection/ingestion
3. collection/ingestion/directory
4. collection/ingestion/directory/zipfile
5. zipfile/directory
6. zipfile/directory/file

(See [The Giant File System](https://docs.google.com/document/d/1obN21_zUF0iNKyLO60XGfvBtx2B2zaFxX1C--uhp2bA/edit#) for more information on this.)

This means the `STARTS WITH` from the ingestion won't match numbers 5 and 6 in the above list.

As Michael said at the time:

> - I think it would be possible to use the same STARTS WITH deletion technique using the blob ID as the prefix

It is, but we need to do it at a point where we've got the blob ID. Typically `deleteIngestion` is called after having deleted all the blobs under that ingestion. So we need to delete blob descendant when we're deleting the blob itself. That's what this PR does.

2022-10-13 10:13 UTC, joelochlann commented
Some neo4j screenshots would be amazing! Thank Phil

2022-10-13 10:46 UTC, philmcmahon requested changes
Actually, looks like there's a bug - r.uri should be children.uri maybe?

2022-10-13 16:27 UTC, joelochlann commented
Good spot! Thanks.

I found another issue too. Have fixed and tested now

2022-10-14 10:08 UTC, philmcmahon approved these changes

2022-10-17 11:11 UTC, merged